# Generated by Django 6.0.5 on 2026-05-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='question_types',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='grade_level',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='number_of_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='total_marks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
