# Generated by Django 6.0.5 on 2026-05-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assignment_question_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='uploaded_file',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/assignments/'),
        ),
    ]
